// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///

namespace Polygon
{
public static class RankingScene_Google
{
        public const string leaderboard_ranking = "CgkI8-z1guIcEAIQAA"; // <GPGSID>
        public const string achievement_sdf = "CgkI8-z1guIcEAIQAg"; // <GPGSID>
        public const string achievement_addasd = "CgkI8-z1guIcEAIQBg"; // <GPGSID>
        public const string achievement_sdff = "CgkI8-z1guIcEAIQAw"; // <GPGSID>
        public const string achievement_zzzz = "CgkI8-z1guIcEAIQBQ"; // <GPGSID>
        public const string achievement_xxx = "CgkI8-z1guIcEAIQBA"; // <GPGSID>

}
}
